using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Facebook_Tool_Request.core
{
    internal class Base
    {
        public static Random rd;
        public static int check = 0;
        public static int width = 0;

        public static int heigh = 0;

        public static int top = 0;

        public static int left = 0;

        public static string useragentDefault = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36";

        public static string base64_anhmau = "/9j/4AAQSkZJRgABAgAAAQABAAD/7QCcUGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAIAcAmcAFGFaalJHblh2SmllZ1pTYWZTalhhHAIoAGJGQk1EMDEwMDBhOTkwMTAwMDBmMTAxMDAwMDM5MDIwMDAwNWEwMjAwMDA4NDAyMDAwMGJmMDIwMDAwMDIwMzAwMDAzMjAzMDAwMDU2MDMwMDAwODgwMzAwMDBmZjAzMDAwMP/bAEMABgQFBgUEBgYFBgcHBggKEAoKCQkKFA4PDBAXFBgYFxQWFhodJR8aGyMcFhYgLCAjJicpKikZHy0wLSgwJSgpKP/bAEMBBwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/CABEIADIAMgMAIgABEQECEQH/xAAaAAEAAwEBAQAAAAAAAAAAAAAAAQMFAgQG/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQD/xAAVAQEBAAAAAAAAAAAAAAAAAAABAP/aAAwDAAABEQIRAAAB+5JS7vRDiPT5kCndc1tq7BzPP1wkoVK/Rrm0HG52vCnjFat1VohQVhxPKf/EAB0QAAICAgMBAAAAAAAAAAAAAAECAxAAEhEgMzH/2gAIAQAAAQUCpYmbDCeo+1P6Wg5ap/Toh2XGOzdIhqmMCpqOPfFULZHOSQ8VF59T9//EABQRAQAAAAAAAAAAAAAAAAAAAED/2gAIAQIRAT8BB//EABQRAQAAAAAAAAAAAAAAAAAAAED/2gAIAQERAT8BB//EAB0QAAIBBAMAAAAAAAAAAAAAAAEQIQARIDACUWH/2gAIAQAABj8CXVROwaAUTiFYvyoc1fihn//EAB8QAAEEAgMBAQAAAAAAAAAAAAEAESExECBRcaFBYf/aAAgBAAABPyHEwzOShxIIQxY3pIO8tpxOjDMOci3YaVS90RgL9w0ElhJRQjf1GQmQNk8jCj45ALA4TA08Y8+1/a//2gAMAwAAARECEQAAEA3owy+Lz2TJQ9PPLf/EABQRAQAAAAAAAAAAAAAAAAAAAED/2gAIAQIRAT8QB//EABcRAAMBAAAAAAAAAAAAAAAAAAARIBD/2gAIAQERAT8QHbx1/8QAIxABAAEDBAICAwAAAAAAAAAAAREAITEQIEFRcYFhkcHw8f/aAAgBAAABPxDQixlOXwVLvhsNIgIGEeNgguED96k9qPb+RsB1ACTU0RlBTrj8bBUKhGR6o5y6R5c0hFsBLTKsytPBxsCQqYAlaMOL0dTQkHCRSpSGBcPjW5UTE8vioQJ25X3q9O3CVeEi68+tP2vndZD2r//Z";

    }
}
