namespace Helpers
{
    public enum KeyCode : ushort
    {
        MEDIA_NEXT_TRACK = 176,
        MEDIA_PLAY_PAUSE = 179,
        MEDIA_PREV_TRACK = 177,
        MEDIA_STOP,
        ADD = 107,
        MULTIPLY = 106,
        DIVIDE = 111,
        SUBTRACT = 109,
        BROWSER_BACK = 166,
        BROWSER_FAVORITES = 171,
        BROWSER_FORWARD = 167,
        BROWSER_HOME = 172,
        BROWSER_REFRESH = 168,
        BROWSER_SEARCH = 170,
        BROWSER_STOP = 169,
        NUMPAD0 = 96,
        NUMPAD1,
        NUMPAD2,
        NUMPAD3,
        NUMPAD4,
        NUMPAD5,
        NUMPAD6,
        NUMPAD7,
        NUMPAD8,
        NUMPAD9,
        F1 = 112,
        F10 = 121,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F2 = 113,
        F20 = 131,
        F21,
        F22,
        F23,
        F24,
        F3 = 114,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        OEM_1 = 186,
        OEM_102 = 226,
        OEM_2 = 191,
        OEM_3,
        OEM_4 = 219,
        OEM_5,
        OEM_6,
        OEM_7,
        OEM_8,
        OEM_CLEAR = 254,
        OEM_COMMA = 188,
        OEM_MINUS,
        OEM_PERIOD,
        OEM_PLUS = 187,
        KEY_0 = 48,
        KEY_1,
        KEY_2,
        KEY_3,
        KEY_4,
        KEY_5,
        KEY_6,
        KEY_7,
        KEY_8,
        KEY_9,
        KEY_A = 65,
        KEY_B,
        KEY_C,
        KEY_D,
        KEY_E,
        KEY_F,
        KEY_G,
        KEY_H,
        KEY_I,
        KEY_J,
        KEY_K,
        KEY_L,
        KEY_M,
        KEY_N,
        KEY_O,
        KEY_P,
        KEY_Q,
        KEY_R,
        KEY_S,
        KEY_T,
        KEY_U,
        KEY_V,
        KEY_W,
        KEY_X,
        KEY_Y,
        KEY_Z,
        VOLUME_DOWN = 174,
        VOLUME_MUTE = 173,
        VOLUME_UP = 175,
        SNAPSHOT = 44,
        RightClick = 93,
        BACKSPACE = 8,
        CANCEL = 3,
        CAPS_LOCK = 20,
        CONTROL = 17,
        ALT,
        DECIMAL = 110,
        DELETE = 46,
        DOWN = 40,
        END = 35,
        ESC = 27,
        HOME = 36,
        INSERT = 45,
        LAUNCH_APP1 = 182,
        LAUNCH_APP2,
        LAUNCH_MAIL = 180,
        LAUNCH_MEDIA_SELECT,
        LCONTROL = 162,
        LEFT = 37,
        LSHIFT = 160,
        LWIN = 91,
        PAGEDOWN = 34,
        NUMLOCK = 144,
        PAGE_UP = 33,
        RCONTROL = 163,
        ENTER = 13,
        RIGHT = 39,
        RSHIFT = 161,
        RWIN = 92,
        SHIFT = 16,
        SPACE_BAR = 32,
        TAB = 9,
        UP = 38
    }

}
