namespace Helpers
{
    public enum VKeys
    {
        VK_A_Cong = 64,
        VK_LBUTTON = 1,
        VK_RBUTTON,
        VK_CANCEL,
        VK_MBUTTON,
        VK_BACK = 8,
        VK_TAB,
        VK_CLEAR = 12,
        VK_RETURN,
        VK_SHIFT = 16,
        VK_CONTROL,
        VK_MENU,
        VK_PAUSE,
        VK_CAPITAL,
        VK_ESCAPE = 27,
        VK_SPACE = 32,
        VK_PRIOR,
        VK_NEXT,
        VK_END,
        VK_HOME,
        VK_LEFT,
        VK_UP,
        VK_RIGHT,
        VK_DOWN,
        VK_SELECT,
        VK_PRINT,
        VK_EXECUTE,
        VK_SNAPSHOT,
        VK_INSERT,
        VK_DELETE,
        VK_HELP,
        VK_0,
        VK_1,
        VK_2,
        VK_3,
        VK_4,
        VK_5,
        VK_6,
        VK_7,
        VK_8,
        VK_9,
        VK_A = 65,
        VK_B,
        VK_C,
        VK_D,
        VK_E,
        VK_F,
        VK_G,
        VK_H,
        VK_I,
        VK_J,
        VK_K,
        VK_L,
        VK_M,
        VK_N,
        VK_O,
        VK_P,
        VK_Q,
        VK_R,
        VK_S,
        VK_T,
        VK_U,
        VK_V,
        VK_W,
        VK_X,
        VK_Y,
        VK_Z,
        VK_NUMPAD0 = 96,
        VK_NUMPAD1,
        VK_NUMPAD2,
        VK_NUMPAD3,
        VK_NUMPAD4,
        VK_NUMPAD5,
        VK_NUMPAD6,
        VK_NUMPAD7,
        VK_NUMPAD8,
        VK_NUMPAD9,
        VK_SEPARATOR = 108,
        VK_SUBTRACT,
        VK_DECIMAL,
        VK_DIVIDE,
        VK_F1,
        VK_F2,
        VK_F3,
        VK_F4,
        VK_F5,
        VK_F6,
        VK_F7,
        VK_F8,
        VK_F9,
        VK_F10,
        VK_F11,
        VK_F12,
        VK_SCROLL = 145,
        VK_LSHIFT = 160,
        VK_RSHIFT,
        VK_LCONTROL,
        VK_RCONTROL,
        VK_LMENU,
        VK_RMENU,
        VK_PLAY = 250,
        VK_ZOOM,
        BM_CLICK = 245,
        VK_OEM_1 = 186,
        VK_OEM_PLUS,
        VK_OEM_COMMA,
        VK_OEM_MINUS,
        VK_OEM_PERIOD,
        VK_OEM_2,
        VK_OEM_3,
        VK_OEM_4 = 219,
        VK_OEM_5,
        VK_OEM_6,
        VK_OEM_7,
        VK_OEM_8
    }

}
